// Generated by Selenium IDE
const { Builder, By, until } = require('selenium-webdriver');
const assert = require('assert');
const fs = require('fs');

describe('10 - 4, should display 6', function () {
    this.timeout(30000);
    let driver;
    let vars;

    if (!fs.existsSync('./screenshots')) {
        fs.mkdirSync('./screenshots');
    }

    beforeEach(async function () {
        const chrome = require('selenium-webdriver/chrome');
        const options = new chrome.Options();
        options.addArguments('--headless', '--no-sandbox', '--disable-dev-shm-usage');
        driver = new Builder().forBrowser('chrome').setChromeOptions(options).build();
        vars = {};
    });


    it('Test 5', async function() {
        await driver.get("http://127.0.0.1:8000/index.html");

        // Wait for num1 to be visible before interacting with it
        let num1Element = await driver.wait(until.elementLocated(By.id("num1")), 10000);
        await driver.wait(until.elementIsVisible(num1Element), 5000);

        let num2Element = await driver.wait(until.elementLocated(By.id("num2")), 10000);
        await driver.wait(until.elementIsVisible(num2Element), 5000);

        // Enter valid numerical values
        await driver.findElement(By.id("num1")).sendKeys("10");
        await driver.findElement(By.id("num2")).sendKeys("4");

        // Click the subtraction button (assuming it's the second button)
        await driver.findElement(By.css("button:nth-child(2)")).click();

        // Wait for the result to appear
        let resultElement = await driver.wait(until.elementLocated(By.id("result")), 5000);
        let resultText = await resultElement.getText();

        // Validate that the result is correctly displayed as "Result: 6"
        assert.strictEqual(resultText, "Result: 6");
    });
});
