name: Java CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build with Maven and Run Integration Tests
        run: |
          cd backend/springboot-backend
          mvn clean spring-boot:run &
          echo "waiting 5 seconds for the server to start"
          sleep 10
          echo "Server ready for testing"
          npm install -g newman
          newman -v
          newman src/test/integration/Calculator Postman.postman_collection.json

    