name: Full Stack CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  full-stack-tests:
    name: Full Stack Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Set up Chrome for Frontend Tests
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
          install-dependencies: true

      # This single step does everything in one shell session:
      - name: Start Backend & Run All Tests
        run: |
          # --- 1) Start the Spring Boot backend in the background ---
          cd backend/springboot-backend
          mvn clean spring-boot:run > backend.log 2>&1 &

          # Wait for backend to start responding
          echo "Waiting for backend to come up..."
          for i in {1..10}; do
            if curl --silent --fail http://localhost:8080/math/add?num1=2&num2=10 ; then
              echo "Backend is up!"
              break
            fi
            echo "Retry #$i: backend not ready yet."
            sleep 3
          done

          # --- 2) Run Postman tests ---
          npm install -g newman
          newman run src/test/integration/calculator.postman_collection.json

          # --- 3) Start frontend server in the background ---
          cd ../../frontend
          npm install
          mkdir -p screenshots
          nohup npx http-server src -p 8000 --host 0.0.0.0 > http-server.log 2>&1 &
          echo "Waiting for frontend..."
          for i in {1..20}; do
            if curl --silent http://localhost:8000 > /dev/null ; then
              echo "Frontend is up!"
              break
            fi
            echo "Retry #$i: frontend not ready yet."
            sleep 2
          done

          # --- 4) Run your browser-based Mocha tests ---
          ./node_modules/.bin/mocha "tests/**/*.spec.js" --timeout 30000

      # Optionally, if you need to upload screenshots or logs:
      - name: Upload Frontend Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: frontend/screenshots/
