- name: Full Stack Tests in One Step
  run: |
    # 1) Build and start the backend in the background
    cd backend/springboot-backend
    mvn clean install
    nohup mvn spring-boot:run > ../../backend.log 2>&1 &
    echo "Waiting for backend..."

    # Wait for the backend
    for i in {1..10}; do
      if curl -s http://localhost:8080/math/add?num1=2&num2=10 ; then
        echo "Backend is up!"
        break
      fi
      echo "Retry #$i: not ready yet"
      sleep 3
    done

    # 2) Run backend (Postman) tests
    npm install -g newman
    newman run src/test/integration/calculator.postman_collection.json
    cd ../..

    # 3) Start the frontend in the background from `frontend/src`
    cd frontend/src
    # Create screenshots folder **one level up** if you want them in `frontend/screenshots`:
    mkdir -p ../screenshots

    python3 -m http.server 8000 &
    echo "Waiting for frontend..."
    for i in {1..10}; do
      if curl -s http://localhost:8000/index.html > /dev/null ; then
        echo "Frontend is up!"
        break
      fi
      sleep 2
    done

    # 4) Go back up to `frontend`, install, then into `tests`
    cd ..
    npm install

    cd tests
    ../node_modules/.bin/mocha "*.js" --timeout 30000
